name: myapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Aquí puedes agregar otras dependencias, como google_fonts
  google_fonts: ^4.0.3

  # Dependencias adicionales
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  
  assets:
    - assets/images/Adventurego.jpg
    - assets/images/asia.jpg
    - assets/images/africa.jpg
    - assets/images/america_norte.jpg
    - assets/images/sudamerica.jpg
    - assets/images/europa.jpg
    - assets/images/oceania.jpg
    - assets/images/safari.jpg
